//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Data.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyTexts() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mod.Data.Localization.MyTexts", typeof(MyTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slim rotor base, used by MA SmartRotors.
        ///
        ///By AutoMcD Astronautical and SISK. ähnelt.
        /// </summary>
        internal static string Description_MA_SmartRotor_Base {
            get {
                return ResourceManager.GetString("Description_MA_SmartRotor_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotor Hinge Base, used by MA SmartRotors.
        ///
        ///By AutoMcD Astronautical and SISK. ähnelt.
        /// </summary>
        internal static string Description_MA_SmartRotor_Base_2 {
            get {
                return ResourceManager.GetString("Description_MA_SmartRotor_Base_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top part to the slim rotor base, used by MA SmartRotors.
        ///
        ///By AutoMcD Astronautical and SISK. ähnelt.
        /// </summary>
        internal static string Description_MA_SmartRotor_Part1 {
            get {
                return ResourceManager.GetString("Description_MA_SmartRotor_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotor Hinge Part, used by MA SmartRotors. By AutoMcD Astronautical and SISK. ähnelt.
        /// </summary>
        internal static string Description_MA_SmartRotor_Part2 {
            get {
                return ResourceManager.GetString("Description_MA_SmartRotor_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smart Rotors: Solar.
        ///
        ///By AutoMcD Astronautical and SISK. ähnelt.
        /// </summary>
        internal static string Description_MA_SmartRotor_Solar {
            get {
                return ResourceManager.GetString("Description_MA_SmartRotor_Solar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smart Rotors: Solar.
        ///Conveyored version for O2 farms.
        ///
        ///Placing this base automatically places all subparts, it tracks the sun automatically, no setup required.
        ///By AutoMcD Astronautical and SISK. ähnelt.
        /// </summary>
        internal static string Description_MA_SmartRotor_Solar_Base {
            get {
                return ResourceManager.GetString("Description_MA_SmartRotor_Solar_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smart Rotors: Solar.
        ///Non-Conveyored version with dual rotor heads.
        ///
        ///Placing this base automatically places all subparts, it tracks the sun automatically, no setup required.
        ///By AutoMcD Astronautical and SISK. ähnelt.
        /// </summary>
        internal static string Description_MA_SmartRotor_Solar_Base_TypeB {
            get {
                return ResourceManager.GetString("Description_MA_SmartRotor_Solar_Base_TypeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Support structure for Solar Panels.
        ///
        ///By AutoMcD Astronautical and SISK. ähnelt.
        /// </summary>
        internal static string Description_MA_Solar_Support {
            get {
                return ResourceManager.GetString("Description_MA_Solar_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slim Rotor Base ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Base {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotor Hinge Base ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Base_2 {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Base_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotor Hinge Base, small grid ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Base_2_sm {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Base_2_sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slim Rotor Base, small grid ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Base_sm {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Base_sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slim Rotor Part ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Part1 {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slim Rotor Part, small grid ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Part1_sm {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Part1_sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotor Hinge Part ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Part2 {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotor Hinge Part, small grid ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Part2_sm {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Part2_sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SmartRotor: Solar ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Solar_Base {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Solar_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SmartRotor: Solar, Type B ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Solar_Base_TypeB {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Solar_Base_TypeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SmartRotor: Solar, Type B small grid ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Solar_Base_TypeB_sm {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Solar_Base_TypeB_sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SmartRotor: Solar Hinge ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Solar_Hinge {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Solar_Hinge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SmartRotor: Solar Hinge, Type B ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Solar_Hinge_TypeB {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Solar_Hinge_TypeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SmartRotor: Solar Hinge, Type B small grid ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Solar_Hinge_TypeB_sm {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Solar_Hinge_TypeB_sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SmartRotor: Solar Hinge Part ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Solar_Part2 {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Solar_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SmartRotor: Solar Hinge Part, Type B ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Solar_Part2_TypeB {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Solar_Part2_TypeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SmartRotor: Solar Hinge Part, Type B small grid ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_SmartRotor_Solar_Part2_TypeB_sm {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_SmartRotor_Solar_Part2_TypeB_sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SmartRotors: Solar Support ähnelt.
        /// </summary>
        internal static string DisplayName_Block_MA_Solar_Support {
            get {
                return ResourceManager.GetString("DisplayName_Block_MA_Solar_Support", resourceCulture);
            }
        }
    }
}
